### ISSUE TITLE
Remove need for Prototype JS in EPrints

### ISSUE THREAD

**Issue by drn05r** [eprints/eprints3.5#22]
A lot of JavaScript functionality was built into EPrints when it was difficult to solve problems with native JavaScript.  With modern browsers this is no longer the case, so we should no longer need to use Prototype JS and should avoid using JQuery for of the core codebase.  This will require rewriting any JavaScript that uses - 

https://github.com/eprints/eprints3.5/tree/master/ingredients/prototypejs/static/javascript/auto

Hopefully, if the way code was written originally core EPrints JS functions for EPrints in https://github.com/eprints/eprints3.5/tree/master/lib/static/javascript and https://github.com/eprints/eprints3.5/tree/master/lib/static/javascript/auto can just be rewritten to use native JavaScript rather than Prototype.  Hopefully the rest of the JavaScript in the core codebase or in Bazaar plugins or ingredients will be using these core EPrints JS functions, so will be unaffected by these underlying implementation changes.

# LINKED ISSUES

Check that eval is not used https://github.com/eprints/eprints3.5/issues/53

**Comment by fatchild** [comment]
**The richtext ingredient has jquery listed as a dependancy**
if we are to move from jquery then we need to consider the parts of richtext which use jquery.

**Comment by fatchild** [comment]
bee12a2c84ae53bf121e7af327e5bd2e68d3ef49

**Comment by fatchild** [comment]
Some prototype js classes extend Lightbox. Although we can probably rewrite Lightbox in vanilla JS, this is out of the scope of this ticket. So I think the best course of action is to create a new ingredient for the Lightbox library file. 
/opt/eprints3/ingredients/prototypejs/static/javascript/auto/40_lightbox.js

**Comment by fatchild** [comment]
Following files are in core, they will need removing
[35_workarounds.js](https://github.com/eprints/eprints3.4/blob/master/ingredients/prototypejs/static/javascript/auto/35_workarounds.js)
[40_lightbox.js](https://github.com/eprints/eprints3.4/blob/master/ingredients/prototypejs/static/javascript/auto/40_lightbox.js)
[45_extras.js](https://github.com/eprints/eprints3.4/blob/master/ingredients/prototypejs/static/javascript/auto/45_extras.js)
