### ISSUE TITLE
Move flavours and ingredients into git sub modules

### ISSUE THREAD

**Issue by fatchild** [eprints/eprints3.5#29]
The following in their own eprints/repo and linked as a submodule for eprints3.5
- pub_lib - https://github.com/eprints/eprints3.4/commit/4de390131a5cb173d2878de165a1a30df94052e9
- easy_pages - Completed as part of #27 06955b40c86201d2e124bcb0498f2f396f9ca3e9
- richtext - Completed as part of #27 06955b40c86201d2e124bcb0498f2f396f9ca3e9
- bazaar - https://github.com/eprints/eprints3.5/pull/38/commits/7bc8653a83051b052733fb1a177f876bd02ca741

The following removed from 3.5 ingredients list once #22 is completed
- jQuery & Prototype

**Comment by fatchild** [comment]
**Adding the submodules to existing and new clones of eprints**

Source: https://gist.github.com/gitaarik/8735255#:~:text=If%20a%20new,initiate%20them%20with%3A

> Getting the submodule's code
> If a new submodule is created by one person, the other people in the team need to initiate this submodule. First you have to get the information about the submodule, this is retrieved by a normal git pull. If there are new submodules you'll see it in the output of git pull. Then you'll have to initiate them with:
> 
> `git submodule init`
> This will pull all the code from the submodule and place it in the directory that it's configured to.
> 
> If you've cloned a repository that makes use of submodules, you should also run this command to get the submodule's code. This is not automatically done by git clone. However, if you add the --recurse-submodules flag, it will.

**Comment by fatchild** [comment]
Move Bazaar ingredient

**Comment by drn05r** [comment]
I would not bother moving the prototypejs ingredient as that should disappear.  I think hold off doing anything with the jquery ingredient for now as well.

**Comment by fatchild** [comment]
Yes, agreed. I had planned to leave those two. I only reopened this to move the bazaar over to it's own repo and include as sub module.
