### ISSUE TITLE
Change format and location of inc file

### ISSUE THREAD

**Issue by fatchild** [eprints/eprints3.5#33]
The current inc file sits within the flavour's root and uses non-standard file markup. By moving to YAML we will have the benefits of a standardised markup syntax and layout and more easily accommodate the versioning of ingredients.

As discussed, we should have an archive level yaml config file. This file can be copied from a flavour level template version when creating a new archive.

**Comment by drn05r** [comment]
This is being done as part of the unified_loader branch and is in PR https://github.com/eprints/eprints3.5/pull/40
